# Generated by Django 2.0.9 on 2019-01-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndyWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VcxConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=30)),
                ('invitation', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(max_length=20)),
                ('connection_data', models.TextField(blank=True, max_length=4000)),
                ('wallet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indyconfig.IndyWallet', to_field='wallet_name')),
            ],
        ),
    ]
