# Generated by Django 2.0.9 on 2019-01-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indywallet',
            name='vcx_config',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
