# Generated by Django 2.0.9 on 2019-01-25 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indyconfig', '0002_indywallet_vcx_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(blank=True, max_length=30, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VcxConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_partner_name', models.CharField(max_length=30)),
                ('conversation_type', models.CharField(max_length=30)),
                ('message_id', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('conversation_data', models.TextField(blank=True, max_length=4000)),
                ('wallet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indyconfig.IndyWallet', to_field='wallet_name')),
            ],
        ),
    ]
