# Generated by Django 2.0.9 on 2019-01-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0003_indysession_vcxconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndyCredentialDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_creddef_id', models.CharField(max_length=40, unique=True)),
                ('creddef_name', models.CharField(max_length=40)),
                ('creddef_handle', models.CharField(max_length=40)),
                ('creddef_template', models.TextField(max_length=4000)),
                ('creddef_data', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='IndySchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_schema_id', models.CharField(max_length=40, unique=True)),
                ('schema_name', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=40)),
                ('schema', models.TextField(max_length=4000)),
                ('schema_data', models.TextField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='indycredentialdefinition',
            name='ledger_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indyconfig.IndySchema'),
        ),
        migrations.AddField(
            model_name='indycredentialdefinition',
            name='wallet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indyconfig.IndyWallet', to_field='wallet_name'),
        ),
    ]
