# Generated by Django 2.0.9 on 2019-01-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0004_auto_20190125_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcxconnection',
            name='connection_type',
            field=models.CharField(default='Outbound', max_length=20),
            preserve_default=False,
        ),
    ]
