# Generated by Django 2.0.9 on 2019-02-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0005_vcxconnection_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcxconversation',
            name='proof_state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
