# Generated by Django 2.0.9 on 2019-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0006_vcxconversation_proof_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='indyschema',
            name='schema_template',
            field=models.TextField(default='{}', max_length=4000),
            preserve_default=False,
        ),
    ]
