# Generated by Django 2.0.9 on 2019-02-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0007_indyschema_schema_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndyProofRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_req_name', models.CharField(max_length=40, unique=True)),
                ('proof_req_description', models.TextField(max_length=4000)),
                ('proof_req_template', models.TextField(max_length=4000)),
            ],
        ),
    ]
