# Generated by Django 2.0.9 on 2019-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0009_auto_20190206_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indyproofrequest',
            name='proof_req_template',
        ),
        migrations.AlterField(
            model_name='indyproofrequest',
            name='proof_req_attrs',
            field=models.TextField(max_length=4000),
        ),
    ]
