# Generated by Django 2.0.10 on 2019-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '0010_auto_20190206_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcxconnection',
            name='token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
