# Generated by Django 2.0.9 on 2019-01-10 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0005_auto_20190110_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriaorganization',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
