# Generated by Django 2.0.9 on 2019-01-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0006_atriaorganization_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcxConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=30)),
                ('partner_name', models.CharField(max_length=30)),
                ('invitation', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(max_length=20)),
                ('connection_data', models.TextField(blank=True, max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='atriaorganization',
            name='vcx_config',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='atriaorganization',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vcx_config',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
