# Generated by Django 2.0.9 on 2019-01-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0007_auto_20190118_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atriaorganization',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
