# Generated by Django 2.0.9 on 2019-01-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indyconfig', '__first__'),
        ('atriacalendar', '0008_auto_20190118_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VcxConnection',
        ),
        migrations.AlterField(
            model_name='atriaorganization',
            name='wallet_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indyconfig.IndyWallet', to_field='wallet_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indyconfig.IndyWallet', to_field='wallet_name'),
        ),
    ]
