# Generated by Django 2.0.9 on 2019-01-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0009_auto_20190120_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atriaorganization',
            name='vcx_config',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vcx_config',
        ),
    ]
