# Generated by Django 2.0.9 on 2019-01-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0012_usersession_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
