# Generated by Django 2.0.9 on 2019-01-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0013_auto_20190124_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
