# Generated by Django 2.0.9 on 2019-01-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0014_auto_20190125_0109'),
        ('atriacalendar', '0006_auto_20190127_1703'),
    ]

    operations = [
    ]
