# Generated by Django 2.0.10 on 2019-02-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0009_auto_20190215_1744'),
        ('atriacalendar', '0016_atriaorganization_org_role'),
    ]

    operations = [
    ]
