# Generated by Django 2.0.10 on 2019-03-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0010_atriaoccurrence'),
        ('atriacalendar', '0017_merge_20190224_2202'),
    ]

    operations = [
    ]
